import Seo from "../components/Seo";
import LegalPage from "../components/LegalPage";

const SECTIONS = [
  {
    id: "summary",
    heading: "The short version",
    body: [
      "Starlight Vanta has no accounts, no sign-in, no advertising and no third-party analytics. Usernames are generated by code running inside your browser, so the names you produce are never transmitted to us and we could not read them if we wanted to.",
      "Two things do involve a server: an anonymous counter of how many names have been generated in total, and donations, which are processed by Stripe.",
    ],
  },
  {
    id: "who",
    heading: "Who is responsible",
    body: [
      "Starlight Vanta is operated by Starlight Solutions, Inc. (“we”, “us”). Questions about this policy can be sent to contact@starsolenterprise.com.",
    ],
  },
  {
    id: "browser",
    heading: "What stays in your browser",
    body: [
      "The following are written to your browser's local storage on the device you are using. They are not cookies, they are not sent with any request, and they are not readable by us or by any other site.",
    ],
    list: [
      "vanta.favorites — names you have bookmarked.",
      "vanta.history — the first few names from each generator run.",
      "vanta.config — your current generator options.",
      "vanta.settings — motion, sound, history and counter preferences.",
      "vanta.taste — the results of the keep-or-pass panel on the home page.",
    ],
  },
  {
    id: "counter",
    heading: "The public counter",
    body: [
      "The home page shows how many names have been generated across all visitors. To keep that figure accurate, your browser sends a small batched message after a generator run containing exactly two things: a count of names produced, and the name of the register used (for example “aesthetic” or “dark”).",
      "No identifier, cookie, device fingerprint or IP address is stored alongside that message. The records are daily totals only, which means there is no row anywhere that corresponds to a person, and no way to reconstruct one. The generated names themselves are never included.",
      "The counter began at a fixed baseline of 5,000 when the public statistics shipped. That offset is disclosed on the home page and is not an estimate of earlier traffic.",
      "You can switch this off entirely under Settings → Public counter. The figure will still be displayed to you; your runs simply will not be added to it.",
    ],
  },
  {
    id: "donations",
    heading: "Donations",
    body: [
      "Donations are processed by Stripe, Inc. When you open the donation form, your card details are entered directly into an element hosted and controlled by Stripe. Those details never pass through this site and are never stored by us.",
      "We receive from Stripe only what is needed to reconcile a payment: the amount, the currency and the payment reference. Stripe processes your information as an independent controller under its own privacy policy, available at stripe.com/privacy.",
      "We do not store a record linking a donation to your use of the generator.",
    ],
  },
  {
    id: "infrastructure",
    heading: "Hosting and security logs",
    body: [
      "The site is served through Vercel and Cloudflare. As with any website, their networks necessarily process the IP address and user-agent of incoming requests in order to deliver the page and to defend against attack. Those records are held by those providers under their own retention policies and are used for delivery and security only.",
      "We do not run our own request logging, and we do not build profiles from any of it.",
    ],
  },
  {
    id: "children",
    heading: "Children",
    body: [
      "Starlight Vanta is not directed at children under 13, and we do not knowingly collect personal information from them. Because the service collects no personal information from any visitor, there is nothing for a parent to request deletion of; if you believe otherwise, write to contact@starsolenterprise.com.",
    ],
  },
  {
    id: "rights",
    heading: "Your rights",
    body: [
      "Data protection law, including the GDPR and the CCPA, gives you rights of access, correction, deletion and portability over personal information held about you.",
      "In practice we hold none. There is no account, no email address on file and no identifier tied to your visit, so there is no record we could return, correct or delete on request. Everything the site has about you is in your own browser, and the Settings page will erase all of it in one action.",
      "We do not sell or share personal information, and we do not use it for targeted advertising, because we do not collect it.",
    ],
  },
  {
    id: "changes",
    heading: "Changes",
    body: [
      "If this policy changes, the date at the top of this page changes with it. Material changes will be described on the page rather than folded in silently.",
    ],
  },
];

export default function Privacy() {
  return (
    <>
      <Seo path="/privacy" />
      <LegalPage
        title="Privacy policy"
        updated="16 September 2026"
        intro={[
          "This policy describes what Starlight Vanta collects, which is close to nothing, and where the few exceptions are.",
        ]}
        sections={SECTIONS}
      />
    </>
  );
}
